spring.application.name=document-management-system

spring.datasource.url=jdbc:postgresql://localhost:5432/staj_db
spring.datasource.username=staj_user
spring.datasource.password=staj_password

# Entity'leri görünce tabloları otomatik oluşturur/günceller
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
